# Generated by Django 2.2.3 on 2019-07-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
